-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. VEHICLES TABLE
create table vehicles (
    id bigint generated by default as identity primary key,
    plateNumber text not null,
    model text,
    department text,
    currentHours numeric default 0,
    currentKm numeric default 0,
    nextMaintenanceHours numeric,
    nextMaintenanceKm numeric,
    maintenanceInterval numeric default 500,
    projectId bigint,
    status text, -- 'active', 'maintenance', etc.
    lastMaintenanceDate date,
    lastMaintenanceHours numeric,
    lastUpdated timestamptz default now()
);

-- 2. LOGS TABLE (Driver Logs)
create table logs (
    id bigint generated by default as identity primary key,
    date date not null,
    assetCode text not null,
    odoHours numeric,
    odoKm numeric,
    notes text,
    maintenanceDone boolean default false,
    maintenanceDescription text,
    createdAt timestamptz default now()
);

-- 3. MAINTENANCE LOGS TABLE
create table maintenance_logs (
    id bigint generated by default as identity primary key,
    vehicleId bigint references vehicles (id),
    date date not null,
    type text, -- 'Bảo dưỡng định kỳ', 'Sửa chữa'
    description text,
    cost numeric default 0,
    performers text,
    createdAt timestamptz default now()
);

-- 4. USERS TABLE
create table users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  role text not null, -- 'admin', 'technician', 'driver'
  name text,
  department text,
  assignedProjects text[], -- Array of strings
  createdAt timestamptz default now()
);

-- 5. PROJECTS TABLE
create table projects (
    id bigint generated by default as identity primary key,
    name text not null,
    code text,
    startDate date,
    endDate date,
    status text
);

-- 6. PARTS TABLE
create table parts (
    id bigint generated by default as identity primary key,
    partNumber text not null,
    name text,
    equivalents text
);

-- 7. ERROR CODES TABLE
create table error_codes (
    id bigint generated by default as identity primary key,
    code text not null,
    description text,
    fixSteps text
);

-- 8. MAINTENANCE SUPPLIES
create table maintenance_supplies (
    id bigint generated by default as identity primary key,
    assetCode text,
    "group" text,
    name text,
    code text,
    donaldsonCode text,
    maintenanceInterval numeric
);

-- 9. CHAT HISTORY (Optional)
create table chat_history (
    id bigint generated by default as identity primary key,
    sessionId text,
    role text,
    content text,
    timestamp timestamptz default now()
);

-- 10. REPORT SNAPSHOTS
create table report_snapshots (
    id bigint generated by default as identity primary key,
    date date,
    stats jsonb
);

-- RLS POLICIES (Row Level Security) - Optional but recommended
alter table vehicles enable row level security;

alter table logs enable row level security;
-- Allow read/write for all (for demo purposes, restrict in production)
create policy "Public Access" on vehicles for all using (true);

create policy "Public Access" on logs for all using (true);

create policy "Public Access" on maintenance_logs for all using (true);

create policy "Public Access" on users for all using (true);

create policy "Public Access" on projects for all using (true);

create policy "Public Access" on parts for all using (true);

create policy "Public Access" on error_codes for all using (true);

create policy "Public Access" on maintenance_supplies for all using (true);

create policy "Public Access" on chat_history for all using (true);

create policy "Public Access" on report_snapshots for all using (true);